"use server";
import bcrypt from "bcryptjs";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/auth";

export async function createMember(formData:FormData){await requireAdmin();const name=String(formData.get("name")||"").trim();const email=String(formData.get("email")||"").trim().toLowerCase();const password=String(formData.get("password")||"");const position=String(formData.get("position")||"").trim()||null;const departmentId=String(formData.get("departmentId")||"")||null;if(!name||!email||password.length<8)throw new Error("بيانات العضو غير مكتملة");const passwordHash=await bcrypt.hash(password,12);await prisma.user.create({data:{name,email,passwordHash,role:"MEMBER",position,departmentId}});revalidatePath("/admin");}
export async function createActivity(formData:FormData){await requireAdmin();const startsAt=new Date(String(formData.get("startsAt")));await prisma.activity.create({data:{title:String(formData.get("title")),description:String(formData.get("description")),location:String(formData.get("location")),startsAt,capacity:Number(formData.get("capacity")),formUrl:String(formData.get("formUrl")),departmentId:String(formData.get("departmentId")||"")||null,status:"PUBLISHED"}});revalidatePath("/admin");revalidatePath("/activities");}
export async function deleteActivity(formData:FormData){await requireAdmin();await prisma.activity.delete({where:{id:String(formData.get("id"))}});revalidatePath("/admin");revalidatePath("/activities");}
export async function saveGuide(formData:FormData){await requireAdmin();const departmentId=String(formData.get("departmentId"));await prisma.departmentGuide.upsert({where:{departmentId},create:{departmentId,overview:String(formData.get("overview")||""),fitFor:String(formData.get("fitFor")||""),careersIncome:String(formData.get("careersIncome")||""),skillsCourses:String(formData.get("skillsCourses")||""),comparisons:String(formData.get("comparisons")||""),faq:String(formData.get("faq")||"")},update:{overview:String(formData.get("overview")||""),fitFor:String(formData.get("fitFor")||""),careersIncome:String(formData.get("careersIncome")||""),skillsCourses:String(formData.get("skillsCourses")||""),comparisons:String(formData.get("comparisons")||""),faq:String(formData.get("faq")||"")}});revalidatePath("/admin");revalidatePath("/departments");}
export async function addStructureItem(formData:FormData){await requireAdmin();await prisma.clubStructureItem.create({data:{name:String(formData.get("name")),title:String(formData.get("title")),level:Number(formData.get("level")||1),sortOrder:Number(formData.get("sortOrder")||0),departmentId:String(formData.get("departmentId")||"")||null}});revalidatePath("/admin");revalidatePath("/delegates");}
