export const EMAIL_VERIFICATION_CODE_LENGTH = 6;
export const EMAIL_VERIFICATION_CODE_TTL_MINUTES =
  10;
export const EMAIL_VERIFICATION_RESEND_SECONDS = 60;
export const EMAIL_VERIFICATION_MAX_ATTEMPTS = 5;
export const EMAIL_VERIFICATION_MAX_SENDS_PER_HOUR =
  5;
