export const PASSWORD_RESET_CODE_LENGTH = 6;
export const PASSWORD_RESET_CODE_TTL_MINUTES = 10;
export const PASSWORD_RESET_RESEND_SECONDS = 60;
export const PASSWORD_RESET_MAX_ATTEMPTS = 5;
export const PASSWORD_RESET_MAX_SENDS_PER_HOUR = 5;
